apiVersion: apps/v1
kind: Deployment
metadata:    
  name: scef-event-listener-deploy
  namespace: rel-iot-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scef-event-listener-pod  
  template:
    metadata:
      labels:
        app: scef-event-listener-pod
    spec:
      containers:
      - image: scef-event-listener:v2
        imagePullPolicy: IfNotPresent
        name: scef-event-listener-app
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
          - containerPort: 7000
      # imagePullSecrets:
      # - name: <secret_name>
      nodeSelector:        
        agentpool: jiopool1
