apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: scef-event-listener-hpa
    namespace: rel-iot-dev
spec:
    scaleTargetRef: 
        apiVersion: apps/v1
        kind: Deployment
        name: scef-event-listener-deploy
    minReplicas: 1
    maxReplicas: 50
    targetCPUUtilizationPercentage: 60